heroes = ['Abaddon', 'Alchemist', 'Ancient Apparition',
            'Anti Mage', 'Arc Warden', 'Axe',
            'Bane', 'Batrider', 'Beastmaster',
            'Bloodseeker', 'Bounty Hunter', 'Brewmaster',
            'Bristleback', 'Broodmother', 'Centaur Warrunner',
            'Chaos Knight', 'Chen', 'Clinkz',
            'Clockwerk', 'Crystal Maiden', 'Dark Seer',
            'Dazzle', 'Death Prophet', 'Disrupter',
            'Doom', 'Dragon Knight', 'Drow Ranger',
            'Earth Spirit', 'Earthshaker', 'Elder Titan',
            'Ember Spirit', 'Enchantress', 'Enigma',
            'Faceless Void', 'Gyrocopter', 'Huskar',
            'Invoker', 'Io', 'Jakiro',
            'Juggernaut', 'Keeper of the Light', 'Kunkka',
            'Legion Commander', 'Leshrac', 'Lich',
            'Lifestealer', 'Lina', 'Lion',
            'Lone Druid', 'Luna', 'Lycan',
            'Magnus', 'Medusa', 'Meepo',
            'Mirana', 'Morphling', 'Naga Siren',
            'Nature\'s Prophet', 'Necrophos', 'Night Stalker',
            'Nyx Assasin', 'Ogre Magi', 'Omniknight',
            'Oracle', 'Outworld Devourer', 'Phantom Assasin',
            'Phantom Lancer', 'Phoenix', 'Puck',
            'Pudge', 'Pugna', 'Queen of Pain',
            'Razor', 'Riki', 'Rubick',
            'Sand King', 'Shadow Demon', 'Shadow Fiend',
            'Shadow Shaman', 'Silencer', 'Skywrath Mage',
            'Slardar', 'Slark', 'Sniper',
            'Spectre', 'Spirit Breaker', 'Storm Spirit',
            'Sven', 'Techies', 'Templar Assasin',
            'Terrorblade', 'Tidehunter', 'Timbersaw',
            'Tinker', 'Tiny', 'Treant Protector',
            'Troll Warlord', 'Tusk', 'Undying',
            'Ursa', 'Vengeful Spirit', 'Venomancer',
            'Viper', 'Visage', 'Warlock',
            'Weaver', 'Windranger', 'Winter Wyvern',
            'Witch Doctor', 'Wraith King', 'Zeus'
            ]

offlane = ['Abaddon', 'Axe', 'Batrider',
            'Beastmaster', 'Brewmaster', 'Bristleback',
            'Broodmother', 'Centaur Warrunner', 'Clinkz',
            'Clockwerk', 'Dark Seer', 'Doom',
            'Earthshaker', 'Faceless Void', 'Legion Commander',
            'Lifestealer', 'Lone Druid', 'Magnus',
            'Mirana', 'Nature\'s Prophet', 'Night Stalker',
            'Nyx Assasin', 'Phoenix', 'Puck',
            'Pudge', 'Queen of Pain', 'Sand King',
            'Slardar', 'Spirit Breaker', 'Tusk',
            'Weaver'
            ]

mid = ['Alchemist', 'Arc Warden', 'Brewmaster',
            'Death Prophet', 'Dragon Knight', 'Drow Ranger',
            'Ember Spirit', 'Huskar', 'Invoker',
            'Juggernaut', 'Kunkka', 'Leshrac',
            'Lina', 'Lone Druid', 'Magnus',
            'Medusa', 'Meepo', 'Mirana',
            'Naga Siren', 'Night Stalker', 'Outworld Devourer',
            'Phantom Assasin', 'Phantom Lancer', 'Puck',
            'Pugna', 'Queen of Pain', 'Razor',
            'Shadow Fiend', 'Sniper', 'Storm Spirit',
            'Templar Assasin', 'Ursa', 'Venomancer',
            'Windranger', 'Zeus'
            ]

carry = ['Alchemist', 'Anti Mage', 'Bloodseeker',
            'Brewmaster', 'Bristleback', 'Chaos Knight',
            'Clinkz', 'Drow Ranger', 'Ember Spirit',
            'Faceless Void', 'Gyrocopter', 'Huskar',
            'Juggernaut', 'Legion Commander', 'Lifestealer',
            'Lone Druid', 'Luna', 'Lycan',
            'Medusa', 'Meepo', 'Mirana',
            'Morphling', 'Naga Siren', 'Necrophos',
            'Phantom Assasin', 'Phantom Lancer', 'Queen of Pain',
            'Razor', 'Silencer', 'Slardar',
            'Slark', 'Spectre', 'Sven',
            'Terrorblade', 'Ursa', 'Weaver',
            'Wraith King'
            ]

support = ['Abaddon', 'Ancient Apparition', 'Bane',
            'Bounty Hunter', 'Chen', 'Crystal Maiden',
            'Dazzle', 'Disrupter', 'Doom',
            'Earth Spirit', 'Earthshaker', 'Elder Titan',
            'Enchantress', 'Enigma', 'Io',
            'Jakiro', 'Keeper of the Light', 'Kunkka',
            'Lich', 'Lina', 'Lion',
            'Mirana', 'Naga Siren', 'Necrophos',
            'Night Stalker', 'Nyx Assasin', 'Ogre Magi',
            'Omniknight', 'Oracle', 'Phoenix',
            'Pudge', 'Pugna', 'Riki',
            'Rubick', 'Sand King', 'Shadow Demon',
            'Shadow Shaman', 'Silencer', 'Skywrath Mage',
            'Spirit Breaker', 'Techies', 'Tusk',
            'Undying', 'Vengeful Spirit', 'Venomancer',
            'Visage', 'Warlock', 'Winter Wyvern',
            'Witch Doctor'
            ]
